/// Flutter icons FixIcons
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:

///
/// 
///
import 'package:flutter/widgets.dart';

class FixIcons {
  FixIcons._();

  static const _kFontFam = 'FixIcons';
  static const  _kFontPkg = null;

  static const IconData mind_fix = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData analyst = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sentinel = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData explorer = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData diplomats = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData shaw = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData diligentia = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
